#!/usr/bin/env python3
"""Migrate a stopped E10 light checkpoint to a new execution-only recipe.

Stop both parent and matching child before invoking. Never kills or launches a
process; only the authoritative stable checkpoint is copied, never working.db.
"""
from argparse import ArgumentParser
from contextlib import closing,ExitStack
from datetime import datetime,timezone
from pathlib import Path
import fcntl,hashlib,json,os,shutil,sqlite3,tempfile
import pycolmap

WORK=Path(__file__).resolve().parent
DATASET=WORK/'datasets/light_shirt_quality'
EXTENSIONS={'.jpg','.jpeg','.png','.bmp','.tif','.tiff'}


def sha(path):
    with Path(path).open('rb') as stream:return hashlib.file_digest(stream,'sha256').hexdigest()


def digest(value):return hashlib.sha256(json.dumps(value,sort_keys=True).encode()).hexdigest()
def clone(value):return json.loads(json.dumps(value))
def now():return datetime.now(timezone.utc).isoformat()


def sync_dir(path):
    fd=os.open(path,os.O_RDONLY)
    try:os.fsync(fd)
    finally:os.close(fd)


def write(path,value):
    with Path(path).open('x') as stream:
        json.dump(value,stream,indent=2,sort_keys=True);stream.write('\n');stream.flush();os.fsync(stream.fileno())


def positive_integer(value,label):
    if not isinstance(value,int) or isinstance(value,bool) or value<1:raise ValueError(f'{label} must be a positive integer')
    return value


def read_pairs(path,names):
    result=[]
    for number,line in enumerate(path.read_text().splitlines(),1):
        line=line.strip()
        if not line or line.startswith('#'):continue
        pair=line.split()
        if len(pair)!=2 or any(name not in names for name in pair) or pair[0]==pair[1]:
            raise ValueError(f'Invalid pair in {path}, line{number}')
        result.append(tuple(sorted(pair)))
    if not result or len(result)!=len(set(result)):raise ValueError('Pair list must be nonempty and unique')
    return result


def image_ids(path):
    with closing(sqlite3.connect(path.as_uri()+'?mode=ro&immutable=1',uri=True)) as database:
        rows=database.execute('SELECT image_id,name FROM images').fetchall()
    result={name:identifier for identifier,name in rows}
    if len(result)!=len(rows) or len({r[0] for r in rows})!=len(rows):raise ValueError('Image names/IDs must be unique')
    return result


def expected_content(dataset,config):
    """Reproduce the immutable manifest generated by the existing API recipe."""
    if config.get('resume_matching') is not True:raise ValueError('Expected a resumable guided E10 recipe')
    threads=positive_integer(config.get('matching_threads',1),'matching_threads')
    batch=positive_integer(config.get('matching_batch_size',128),'matching_batch_size')
    baseline=(dataset/config['baseline_dataset']).resolve();boxes=(dataset/config['boxes']).resolve()
    image_root=(dataset/'images').resolve();images=sorted(p for p in image_root.rglob('*') if p.is_file() and p.suffix.lower() in EXTENSIONS)
    names=[p.relative_to(image_root).as_posix() for p in images]
    baseline_db=baseline/'colmap/database.db'
    baseline_files=[baseline_db]+sorted(p for p in (baseline/'colmap/sparse').rglob('*') if p.is_file())
    signature={'recipe_version':1,'images':[[name,p.stat().st_size,p.stat().st_mtime_ns] for name,p in zip(names,images)],
        'pycolmap':pycolmap.__version__,'baseline':[[str(p),p.stat().st_size,p.stat().st_mtime_ns] for p in baseline_files],
        'boxes_sha256':sha(boxes),'extraction':{'max_image_size':-1,'num_threads':1,
            'sift':{'first_octave':-1,'max_num_features':16384,'peak_threshold':.004,'estimate_affine_shape':True,'domain_size_pooling':True,'dsp_num_scales':10}},
        'crop_padding':32,'spatial_cells':[8,16],'max_features':positive_integer(config.get('max_features',18000),'max_features')}
    feature_key=digest(signature);cache=dataset/'colmap/quality_feature_cache'
    feature=cache/(feature_key+'.db');metadata=cache/(feature_key+'.json')
    saved=json.loads(metadata.read_text())
    if saved.get('signature')!=signature or saved.get('database_size')!=feature.stat().st_size:
        raise ValueError('Feature checkpoint signature/size disagrees with current inputs')
    for path in (feature,baseline_db):
        wal=Path(str(path)+'-wal')
        if wal.exists() and wal.stat().st_size:raise ValueError(f'Input database has a nonempty WAL: {path}')
    expected_images=image_ids(baseline_db)
    if set(expected_images)!=set(names) or image_ids(feature)!=expected_images:
        raise ValueError('Feature/baseline image identities disagree with the current image files')
    ordinary=(dataset/config['matching_pairs']).resolve();guided=(dataset/config['guided_pairs']).resolve()
    pairs=read_pairs(ordinary,expected_images);guided_pairs=read_pairs(guided,expected_images)
    if pairs!=guided_pairs:raise ValueError('E10 requires identical ordered all-pair ordinary and guided lists')
    if len(pairs)!=len(names)*(len(names)-1)//2:raise ValueError('E10 pair coverage is not exhaustive')
    expected_ids={int(pycolmap.image_pair_to_pair_id(expected_images[a],expected_images[b])) for a,b in pairs}
    if len(expected_ids)!=len(pairs):raise ValueError('Pair IDs are not unique')
    matching=pycolmap.FeatureMatchingOptions({'num_threads':threads,'guided_matching':True,'use_gpu':False}).todict()
    pairing=pycolmap.ImportedPairingOptions({'block_size':min(32,batch)}).todict()
    pairing['match_list_path']='<current batch pair file>'
    recipe=json.loads(json.dumps({'checkpoint_version':1,'features':feature_key,'pycolmap':pycolmap.__version__,'device':'cpu',
        'matching_pairs_sha256':sha(ordinary),'guided_pairs_sha256':sha(guided),'matching_options':matching,
        'verification_options':pycolmap.TwoViewGeometryOptions().todict(),'pairing_options':pairing,'matching_batch_size':batch},default=str))
    content={'recipe':recipe,'feature_database_sha256':sha(feature),'images':sorted([name,i] for name,i in expected_images.items()),'total_pairs':len(pairs)}
    return content,expected_images,expected_ids,feature


def select_source(cache,expected):
    candidates=[]
    for path in sorted(cache.glob('*/manifest.json')):
        try:
            manifest=json.loads(path.read_text());content={k:v for k,v in manifest.items() if k!='checkpoint_key'}
        except (OSError,ValueError,TypeError):continue
        if content!=expected:continue
        key=digest(content)
        if manifest.get('checkpoint_key')!=key or path.parent.name!=key:
            raise ValueError('Matching source immutable recipe/key is invalid')
        if path.is_symlink() or path.parent.is_symlink():raise ValueError('Source checkpoint/manifest must be independent files')
        candidates.append((path,manifest))
    if len(candidates)!=1:raise ValueError(f'Expected exactly one checkpoint for current workers, batch, pairs and inputs; found{len(candidates)}')
    return candidates[0]


def validate_database(path,names,expected_ids,expected_completed=None):
    if path.name!='checkpoint.db' or not path.is_file() or path.is_symlink():raise ValueError('Only a real stable checkpoint.db may be migrated')
    for suffix in ('-wal','-journal'):
        sidecar=Path(str(path)+suffix)
        if sidecar.exists() and sidecar.stat().st_size:raise ValueError('Stable checkpoint has a nonempty WAL/journal')
    with closing(sqlite3.connect(path.as_uri()+'?mode=ro&immutable=1',uri=True)) as database:
        if database.execute('PRAGMA quick_check').fetchall()!=[('ok',)]:raise ValueError('Source checkpoint SQLite quick_check failed')
        image_rows=database.execute('SELECT image_id,name FROM images').fetchall()
        if len(image_rows)!=len(names) or {name:i for i,name in image_rows}!=names:raise ValueError('Checkpoint image IDs/names disagree with recipe')
        raw_rows=database.execute('SELECT pair_id FROM matches').fetchall();geometry_rows=database.execute('SELECT pair_id FROM two_view_geometries').fetchall()
    raw={r[0] for r in raw_rows};geometry={r[0] for r in geometry_rows}
    if len(raw)!=len(raw_rows) or len(geometry)!=len(geometry_rows):raise ValueError('Duplicate pair IDs in checkpoint')
    if raw!=geometry or not raw<=expected_ids:raise ValueError('Checkpoint contains foreign or incompletely paired rows')
    if expected_completed is not None and raw!=expected_completed:raise ValueError('Copied completed pair IDs changed')
    return raw


def changed_recipe(content,workers,batch):
    new=clone(content);old_recipe=content['recipe'];recipe=new['recipe'];changes={}
    if old_recipe['matching_options']['num_threads']!=workers:
        changes['num_threads']={'before':old_recipe['matching_options']['num_threads'],'after':workers}
    if old_recipe['matching_batch_size']!=batch:
        changes['matching_batch_size']={'before':old_recipe['matching_batch_size'],'after':batch}
    if old_recipe['pairing_options']['block_size']!=min(32,batch):
        changes['pairing_options.block_size']={'before':old_recipe['pairing_options']['block_size'],'after':min(32,batch)}
    recipe['matching_options']['num_threads']=workers;recipe['matching_batch_size']=batch;recipe['pairing_options']['block_size']=min(32,batch)
    restored=clone(new);restored['recipe']['matching_options']['num_threads']=old_recipe['matching_options']['num_threads']
    restored['recipe']['matching_batch_size']=old_recipe['matching_batch_size'];restored['recipe']['pairing_options']['block_size']=old_recipe['pairing_options']['block_size']
    if restored!=content:raise AssertionError('Migration changed algorithmic settings')
    return new,changes


def migrate(work=WORK,dataset=DATASET,workers=4,batch_size=None):
    work,dataset=Path(work).resolve(),Path(dataset).resolve();cache=dataset/'colmap/quality_matching_cache'
    if workers not in (1,2,4) or isinstance(workers,bool):raise ValueError('Workers must be1,2 or4')
    if batch_size is not None:positive_integer(batch_size,'batch_size')
    config_path=dataset/'sfm_refine.json'
    # The parent runner and child checkpoint each own one existing advisory lock.
    # Caller stops both; these nonblocking guards never kill/wait on processes.
    with ExitStack() as stack:
        runner_lock=stack.enter_context((work/'runner.lock').open('a+'))
        fcntl.flock(runner_lock.fileno(),fcntl.LOCK_EX|fcntl.LOCK_NB)
        config_hash=sha(config_path);config=json.loads(config_path.read_text())
        content,names,expected_ids,feature=expected_content(dataset,config)
        batch=content['recipe']['matching_batch_size'] if batch_size is None else batch_size
        source_manifest_path,old=select_source(cache,content);source=source_manifest_path.parent;source_key=old['checkpoint_key']
        source_lock_path=cache/(source_key+'.lock')
        if not source_lock_path.is_file() or source_lock_path.is_symlink():raise ValueError('Existing source checkpoint lock is required')
        lock=stack.enter_context(source_lock_path.open('r+'))
        fcntl.flock(lock.fileno(),fcntl.LOCK_EX|fcntl.LOCK_NB)
        if sha(config_path)!=config_hash or json.loads(source_manifest_path.read_text())!=old:raise RuntimeError('Source recipe/config changed during selection')
        database=source/'checkpoint.db';completed=validate_database(database,names,expected_ids)
        database_hash,manifest_hash=sha(database),sha(source_manifest_path)
        new_content,changes=changed_recipe(content,workers,batch);target_key=digest(new_content);target=cache/target_key
        if target.exists() or target.is_symlink():raise FileExistsError(f'Preserving existing checkpoint:{target}; choose a new execution batch size if needed')
        target_lock=stack.enter_context((cache/(target_key+'.lock')).open('a+'))
        fcntl.flock(target_lock.fileno(),fcntl.LOCK_EX|fcntl.LOCK_NB)
        after=dict(config,matching_threads=workers,matching_batch_size=batch)
        config_changes={k:{'before':config.get(k),'after':after[k]} for k in ('matching_threads','matching_batch_size') if config.get(k)!=after[k]}
        restored=dict(after)
        for k in ('matching_threads','matching_batch_size'):
            if k in config:restored[k]=config[k]
            else:restored.pop(k,None)
        if restored!=config:raise AssertionError('Configuration changed beyond execution settings')
        with tempfile.TemporaryDirectory(prefix='.worker_change_',dir=cache) as temporary:
            staged=Path(temporary)/'checkpoint';staged.mkdir();copied=staged/'checkpoint.db'
            shutil.copy2(database,copied)
            with copied.open('rb') as stream:os.fsync(stream.fileno())
            if sha(copied)!=database_hash or (copied.stat().st_dev,copied.stat().st_ino)==(database.stat().st_dev,database.stat().st_ino):
                raise AssertionError('Checkpoint copy is not independent and byte-identical')
            validate_database(copied,names,expected_ids,completed)
            write(staged/'manifest.json',dict(new_content,checkpoint_key=target_key))
            write(staged/'progress.json',{'checkpoint_key':target_key,'checkpoint_database':str(target/'checkpoint.db'),
                'updated_utc':now(),'phase':'matching_complete' if completed==expected_ids else 'matching','complete':completed==expected_ids,
                'total_pairs':old['total_pairs'],'completed_pairs':len(completed),'remaining_pairs':len(expected_ids-completed),
                'matching_threads':workers,'matching_batch_size':batch,'guided_matching':True,'last_committed_batch_pairs':0,
                'note':'Verified inheritance of complete guided pairs from a stopped stable checkpoint; parent checkpoint preserved.'})
            sync_dir(staged)
            if sha(database)!=database_hash or sha(source_manifest_path)!=manifest_hash or sha(feature)!=old['feature_database_sha256'] or sha(config_path)!=config_hash:
                raise RuntimeError('Immutable source/config changed during checkpoint copy')
            if target.exists():raise FileExistsError(f'Target appeared during copy:{target}')
            staged.rename(target);sync_dir(cache)
        record={'created_utc':now(),'reason':'Authorized execution-only worker/batch change with all committed guided pairs preserved.',
            'source_checkpoint_dir':str(source),'target_checkpoint_dir':str(target),'source_checkpoint_key':source_key,'target_checkpoint_key':target_key,
            'source_manifest_sha256':manifest_hash,'target_manifest_sha256':sha(target/'manifest.json'),
            'source_checkpoint_sha256':database_hash,'target_initial_checkpoint_sha256':sha(target/'checkpoint.db'),
            'completed_pairs_transferred':len(completed),'transferred_pair_ids_sha256':digest(sorted(completed)),
            'only_matching_option_changed':changes,'source_feature_database_sha256':old['feature_database_sha256'],
            'config_before':config,'config_after':after,'config_only_execution_changes':True,'only_config_options_changed':config_changes,
            'scope':f'Light shirt only; all{old["total_pairs"]:,} pairs, guided ON, identical features and thresholds, consensus90 final output.'}
        migrations=work/'worker_migrations';migrations.mkdir(exist_ok=True)
        record_path=migrations/(datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%S.%fZ')+'.json')
        write(record_path,record);sync_dir(migrations)
        fd,temp_name=tempfile.mkstemp(prefix='.sfm_refine_worker_',suffix='.json',dir=dataset);os.close(fd);temporary_config=Path(temp_name)
        try:
            temporary_config.unlink();write(temporary_config,after)
            if sha(config_path)!=config_hash:raise RuntimeError('Configuration changed before atomic publication')
            os.replace(temporary_config,config_path);sync_dir(dataset)
        finally:temporary_config.unlink(missing_ok=True)
        if sha(database)!=database_hash or sha(source_manifest_path)!=manifest_hash:raise RuntimeError('Parent checkpoint changed')
        return {'record':str(record_path),'preserved_pairs':len(completed),'remaining_pairs':len(expected_ids-completed),
            'matching_threads':workers,'matching_batch_size':batch,'new_checkpoint':str(target)}


def main():
    parser=ArgumentParser(description=__doc__);parser.add_argument('--workers',type=int,choices=(1,2,4),required=True)
    parser.add_argument('--batch-size',type=int)
    args=parser.parse_args()
    if args.batch_size is not None and args.batch_size<1:parser.error('--batch-size must be positive')
    print(json.dumps(migrate(workers=args.workers,batch_size=args.batch_size),indent=2))

if __name__=='__main__':main()
